name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    env:
      SSH_KEY: $
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # INSTALL
      - name: install modules
        run: yarn install
      # BUILD
      - name: build project
        run: yarn build
      # SSH
      - run: mkdir ~/.ssh
      - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e "Host static\n\tUser github-actions-tutorial\n\tHostname 5.189.239.236.\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
