name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master, stage ]
  pull_request:
    branches: [ master, stage ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      # CREATE NODE SERVER
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          sudo chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -p 32522 5.189.239.236 >> ~/.ssh/known_hosts
#          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
#          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

#      - name: copy file via ssh key
#        uses: appleboy/scp-action@master
#        env:
#          HOST:  ${{ secrets.HOST }}
#          USERNAME:  ${{ secrets.USERNAME }}
#          PORT:  ${{ secrets.PORT }}
#          PASSWORD: ${{ secrets.PASSWORD }}
#        with:
#          source: "./ghost"
#          target: "/var/www/test"
#          strip_components: 2

          #      - name: Configure SSH
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_KEY" > ~/.ssh/staging.key
#          chmod 600 ~/.ssh/staging.key
#          cat >>~/.ssh/config <<END
#          Host staging
#            HostName 5.189.239.236
#            User $SSH_USER
#            IdentityFile ~/.ssh/staging.key
#            StrictHostKeyChecking no
#          END
#        env:
#          SSH_USER: ${{ secrets.SSH_USER }}
#          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#      - run: mkdir ~/.ssh
#      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
#      - run: chmod 700 ~/.ssh/id_rsa
#      - run: ssh-keyscan -t rsa -p 32522 5.189.239.236 >> ~/.ssh/known_hosts
#      - run: echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
#      - run: chmod 644 ~/.ssh/known_hosts
#
#      - run: which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
#      - run: mkdir -p ~/.ssh
#      - run: echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#      - run: chmod 700 ~/.ssh/id_rsa
#      - run: eval `ssh-agent -s`; ssh-add ~/.ssh/id_rsa
#      - run: ssh-keyscan -t rsa 'root@wis-software.ru -p 32522' > ~/.ssh/known_hosts
#      - run: echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#      - run: chmod 644 ~/.ssh/known_hosts
      # INSTALL
      - name: install modules
        run: yarn install
      # BUILD
      - name: build project
        run: yarn build
      # CREATE SSH
#      - run: mkdir -p ~/.ssh/
#      - run: echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
#      - run: chmod 600 ~/.ssh/id_rsa
#      - run: ssh-keyscan -t rsa 'root@wis-software -p 32522' >> ~/.ssh/known_hosts

      # SSH
      - run : sshpass -p '123456' scp -r -P 32522 -o StrictHostKeyChecking=no build/* root@5.189.239.236:/var/www/test

