name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master, stage ]
  pull_request:
    branches: [ master, stage ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      # CREATE NODE SERVER
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # INSTALL
      - name: install modules
        run: yarn install
      # BUILD
      - name: build project
        run: yarn build
      # SSH
      - run : sshpass -p '123456' -P assphrase scp -r -P 32522 build/* root@5.189.239.236:/var/www/test
#      - run: scp -r -P ${{ secrets.SSH_PORT_PROD }} build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test
#      - run: sshpass -p ${{ secrets.PASSPHRASE }} -P assphrase scp -r -P ${{ secrets.SSH_PORT_PROD }} build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test
#      - name: install ssh key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          name: is_rsa
#          known_hosts: ${{ secrets.KNOWN_HOSTS }}
#      - name: adding Known Hosts
#        run: ssh-keyscan -p ${{ secrets.SSH_PORT_PROD }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
#      - name: deploy with rsync
#        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT_PROD }}" build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test

#      - run: mkdir -p ~/.ssh
#      - run: echo "$SSH_KEY" >> ~/.ssh/github-action
#      - run: chmod 700 ~/.ssh/github-action
#      - run: echo -e "Host static\n\tUser github-actions-tutorial\n\tHostname 5.189.239.236\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config

#  prod:
#    if: ${{ github.ref == 'ref/heads/master' }}
#    steps:
#      - name: it is master branch
#      - run: scp -r -P 32522 build/* root@wis-software.ru:/var/www/test
#      - run: echo "finish"
#
#  stage:
#    if: ${{ github.ref == 'ref/heads/stage' }}
#    steps:
#      - name: it is stage branch
#      - run: scp -r -P 42522 build/* root@wis-software.ru:/var/www/test2
#      - run: echo "finish"
