name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
      - stage
  pull_request:
    branches:
      - master
      - stage
jobs:
  deploing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
      - name: master
        if: ${{ github.ref == 'refs/heads/master' }}
        run:
          ssh-keyscan -t rsa -p ${{ secrets.SSH_PORT_PROD }} ${{ secrets.SSH_IP_ADDRESS }} >> ~/.ssh/known_hosts
      - name: stage
        if: ${{ github.ref == 'refs/heads/stage' }}
        run:
          ssh-keyscan -t rsa -p ${{ secrets.SSH_PORT_STAGE }} ${{ secrets.SSH_IP_ADDRESS }} >> ~/.ssh/known_hosts
      - run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          chmod 644 ~/.ssh/known_hosts
      - name: install modules
        run: yarn install
      - name: build project
        run: yarn build
      - name: deploy to master
        if: ${{ github.ref == 'refs/heads/master' }}
        run: scp -r -P ${{ secrets.SSH_PORT_PROD }} build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_NAME }}:/var/www/test
      - name: deploy to stage
        if: ${{ github.ref == 'refs/heads/stage' }}
        run: scp -r -P ${{ secrets.SSH_PORT_STAGE }} build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_NAME }}:/var/www/test
